title: Nikolai Dvurechensky ğŸ‘‹
description: â­
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jemoji
  - jekyll-mentions
paginate: 5
collections:
  categories:
    output: true
include:
  - assets/css/custom.css
